import 'package:meo_traker/core/constants/food_select_category.dart';

/// Món đủ điều kiện / sẵn có địa phương (chỉ tên món).
const List<FoodSelectCategory> kEligibleFoodCategories = [
  FoodSelectCategory(
    title: 'Nguồn Đạm (Protein) hằng ngày',
    items: [
      'Cá điêu hồng',
      'Cá hú',
      'Cá lóc đồng/nuôi',
      'Cá trê',
      'Cá rô đồng',
      'Cá ngát',
      'Cá bạc má',
      'Cá nục',
      'Cá thác lác (nạo sẵn)',
      'Tép bạc / Tép trấu',
      'Cua đồng',
      'Hến sông',
      'Ốc bươu',
      'Trứng vịt / Trứng gà',
      'Trứng cút',
      'Thịt heo xay',
      'Thịt nách / Thịt dăm heo',
      'Sườn non heo / Xương cổ',
      'Ức gà công nghiệp',
      'Đùi gà góc tư',
      'Gan heo',
      'Huyết heo / Huyết vịt',
      'Đậu hũ trắng / Đậu hũ chiên',
      'Nấm rơm',
      'Nấm bào ngư',
    ],
  ),
  FoodSelectCategory(
    title: 'Rau xanh & Củ quả',
    items: [
      'Rau muống',
      'Rau lang',
      'Rau dền (đỏ/xanh)',
      'Mồng tơi',
      'Rau ngót',
      'Cải ngọt',
      'Cải bẹ xanh',
      'Cải thìa',
      'Bắp cải',
      'Rau má',
      'Bông súng',
      'Bông bí',
      'Rau đắng đất',
      'Bắp chuối',
      'Kèo nèo',
      'Đọt nhãn lồng',
      'Đọt choại',
      'Lá cách',
      'Giá đỗ',
      'Hẹ lá',
      'Bí đỏ',
      'Bí đao',
      'Bầu',
      'Mướp hương',
      'Khổ qua',
      'Cà chua',
      'Dưa leo',
      'Đậu cô ve',
      'Đậu bắp',
      'Củ cải trắng / Củ cải đỏ (Cà rốt)',
      'Đu đủ xanh',
      'Củ sắn (Củ đậu)',
      'Củ sen',
      'Su su',
      'Súp lơ trắng/xanh',
    ],
  ),
  FoodSelectCategory(
    title: 'Tinh bột & Ngũ cốc',
    items: [
      'Gạo tẻ dẻo',
      'Gạo lứt',
      'Khoai lang Trà Vinh',
      'Khoai mì (Sắn)',
      'Khoai môn',
      'Bắp nếp / Bắp Mỹ',
      'Bún tươi',
      'Bánh canh bột xắt',
      'Bánh tráng (loại mỏng)',
      'Đậu phộng (Lạc)',
      'Đậu xanh',
      'Đậu đen / Đậu đỏ',
      'Mè đen / Mè trắng',
      'Hủ tiếu khô / Mì gói',
      'Bột nếp / Bột gạo',
    ],
  ),
  FoodSelectCategory(
    title: 'Trái cây tươi & Nước giải nhiệt',
    items: [
      'Chuối xiêm / Chuối cau',
      'Đu đủ chín',
      'Dưa hấu',
      'Khóm (Thơm)',
      'Ổi',
      'Thanh long',
      'Cam sành',
      'Trái tắc (Hạnh)',
      'Dừa xiêm',
      'Mía tươi',
    ],
  ),
  FoodSelectCategory(
    title: 'Cặp món ăn hoàn chỉnh hằng ngày',
    items: [
      'Cá lóc kho tộ + Canh chua bắp chuối cá lóc',
      'Trứng chiên hành tây + Canh bí đỏ thịt băm',
      'Thịt nách heo luộc + Rau rừng cuốn bánh tráng',
      'Cá điêu hồng chiên giòn + Canh cải bẹ xanh gừng',
      'Đậu hũ sốt cà chua + Canh rau ngót nấu tép',
      'Thịt kho tiêu + Canh mướp mồng tơi tôm khô',
      'Cá rô kho quẹt + Đậu bắp, bầu luộc',
      'Gà kho gừng + Canh đu đủ hầm xương cổ',
      'Tép rang lá chanh + Canh chua lá me non',
      'Mực trứng/Bạch tuộc xào dưa leo cà chua',
      'Mắm chưng hột vịt + Rau sống chuối chát',
      'Canh hẹ huyết heo đậu hũ + Thịt băm xào đọt choại',
      'Bún xào thịt băm giá hẹ',
      'Cháo cá lóc rau đắng',
      'Khoai lang luộc + Nước đậu đen rang',
    ],
  ),
];
