import 'package:meo_traker/core/constants/food_select_category.dart';

/// Danh mục nguồn thực phẩm địa phương Trà Vinh (chỉ tên món).
const List<FoodSelectCategory> kLocalFoodCategories = [
  FoodSelectCategory(
    title: 'Món ăn sáng & Món nước bình dân',
    items: [
      'Bún nước lèo Trà Vinh',
      'Bún suông',
      'Bún gỏi da',
      'Bánh canh Bến Có',
      'Bánh canh xắt thịt vịt',
      'Bún mắm miền Tây',
      'Bún xào thịt heo / chả giò',
      'Cơm tấm sườn bì chả',
      'Cơm dừa Trà Vinh',
      'Hủ tiếu Nam Vang',
      'Hủ tiếu hấp',
      'Bánh xèo dừa / tép đất',
      'Bánh khọt nhân tép',
      'Cháo lòng bánh hỏi',
      'Cháo cá lóc rau đắng',
      'Cháo gà xé phay / cháo vịt',
      'Lẩu mắm',
      'Lẩu bần Trà Vinh',
      'Lẩu măng chua cá hú / cá bớp',
      'Bánh hỏi thịt heo quay',
      'Mì gõ / Mì hoành thánh',
      'Bún riêu cua đồng',
      'Bún mọc / Bún mắm nêm',
      'Cơm phần bình dân',
      'Bánh mì pate thịt nướng',
    ],
  ),
  FoodSelectCategory(
    title: 'Bánh dân gian, Món ăn vặt & Chè',
    items: [
      'Bánh tét Trà Cuôn',
      'Bánh ống Khmer',
      'Bánh giá (bánh rái)',
      'Bánh đúc mặn',
      'Bánh đúc ngọt',
      'Bánh bò thốt nốt',
      'Bánh lợt nước cốt dừa',
      'Bánh ít nhân dừa / nhân đậu',
      'Bánh chuối nướng / chuối hấp',
      'Chuối nếp nướng nước cốt dừa',
      'Bánh da lợn lá cẩm / lá nếp',
      'Chè bưởi',
      'Chè thốt nốt dừa tươi',
      'Chè đậu xanh bánh trôi nước',
      'Chè sương sa hạt lựu',
      'Sâm bổ lượng',
      'Bánh cam / bánh còng',
      'Chuối chiên / Khoai lang chiên',
      'Bánh tráng nướng mắm quốc',
      'Bánh tráng trộn Sa Cát / bình dân',
    ],
  ),
  FoodSelectCategory(
    title: 'Rau củ & Rau dại sông nước',
    items: [
      'Rau đắng đất',
      'Kèo nèo (tai tượng)',
      'Bông điên điển',
      'Bông súng',
      'Rau muống đồng',
      'Rau dừa nước',
      'Rau càng cua',
      'Bắp chuối (hoa chuối)',
      'Giá đỗ tự nhiên',
      'Dưa leo / Cà chua bãi bồi',
      'Đọt khổ qua rừng',
      'Đọt xoài / Đọt cóc',
      'Lá cách',
      'Củ sắn (củ đậu)',
      'Khoai lang Trà Vinh',
      'Khoai môn / Khoai sọ',
      'Bắp nếp luộc',
      'Đậu xanh / Đậu đen địa phương',
      'Đọt lang luộc',
      'Rau đắng biển',
    ],
  ),
  FoodSelectCategory(
    title: 'Cá, Tôm & Thủy hải sản địa phương',
    items: [
      'Cá lóc đồng',
      'Cá rô đồng',
      'Cá hú / Cá tra sông',
      'Cá trê đồng',
      'Cá linh',
      'Cá sặc ranh / Cá sặc bổi',
      'Cá kèo',
      'Tép đất / Tép sông',
      'Tép bạc',
      'Cua đồng',
      'Ba khía Trà Vinh',
      'Ốc bươu đồng',
      'Ốc đắng',
      'Hến sông',
      'Cá thòi lòi / Cá chẽm',
    ],
  ),
  FoodSelectCategory(
    title: 'Trái cây tươi & Nông sản giải nhiệt',
    items: [
      'Dừa xáp Trà Vinh (Cầu Kè)',
      'Dừa xiêm / Dừa dứa',
      'Trái bần chua',
      'Trái thốt nốt',
      'Cam xoàn Cầu Kè',
      'Bưởi da xanh',
      'Chuối xiêm / Chuối cau',
      'Xoài cát Chu / Xoài Tượng',
      'Đu đủ chín / Đu đủ hầm xương',
      'Trái thanh long',
      'Ổi Đài Loan / Ổi xá lị',
      'Mãng cầu ta / Mãng cầu gai',
    ],
  ),
  FoodSelectCategory(
    title: 'Mắm, Khô & Gia vị truyền thống',
    items: [
      'Mắm bò hóc (Prohok)',
      'Mắm cá sặc',
      'Mắm cá lóc',
      'Khô cá lóc Trà Vinh',
      'Khô cá sặc bổi',
      'Tôm khô Duyên Hải',
      'Lạp xưởng Trà Vinh',
      'Đường thốt nốt nguyên chất',
    ],
  ),
];
